### PR TITLE
Replace src/ios/GCDWebServer with git submodule.

### PR DESCRIPTION
**Pull request by benjamn**
It's much easier to maintain a fork of https://github.com/swisspol/GCDWebServer (that is, https://github.com/meteor/GCDWebServer) and include it in this repository as a submodule, potentially with additional commits cherry-picked in, than to maintain a copy of the code within this repository.

### CODE REVIEW

**Comment by KoenLav** [comment]
Much better indeed 👍

**Comment by KoenLav** [comment]
Might be nice to commit the "current" state of GCDWebserver to a branch in the new (forked) repository, so we can see any differences.

**Comment by KoenLav** [comment]
The modified GCDWebserver in this repository, that is.

**Comment by benjamn** [comment]
I've published this version to npm as `cordova-plugin-meteor-webapp@1.5.0`, in case anyone wants to play with it (just edit `meteor/packages/webapp/package.js` to change the version).

**Comment by abernix** [comment]
I'm curious if developers will experience problems installing this plugin from a Git URL, ala:

    meteor add cordova:cordova-plugin-meteor-webapp@https://github.com/...

...will encounter problems since Cordova bundles `npm@2` prior to Cordova 8 (which Meteor has yet to jump to) and Git submodule support was less robust (missing?) in those earlier (read: old) versions of npm.  Even if this is the case, it will hopefully be temporary since as of Cordova 8 it no longer bundles npm and falls back to the "system npm", which in Meteor's case, should be "Meteor's version of npm".

Anyhow, just a thought.

**Comment by hwillson** [comment]
I just tried creating and running a brand new app:

```
meteor create mobile-test
meteor add-platform ios
meteor run ios-device
```

using `cordova-plugin-meteor-webapp@1.5.0` and the `devel` branch, and was immediately hit with the following error:

```
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

This prevented the app from running. This is the same error that was reported in https://github.com/meteor/cordova-plugin-meteor-webapp/issues/34. Is anyone else seeing this? I'll keep debugging to see if it's just an issue with my environment, but just a heads up.

**Comment by iwoj** [comment]
I'm also having this problem (in 1.6.0). It's holding us back from deploying my meteor app to the ios app store. It's critical for us.

**Pull request merged**
