### PR TITLE
Updated swift code to be compatible to version 4.2

### PR DESCRIPTION
**Pull request by rj-david**
For preparation to move from swift 3.0

These changes were as suggested by xcode

### CODE REVIEW

**Comment by Nauzer** [comment]
Glad this is resolved with changes to meteor-webapp 👍 
Haven't updated to 10.2 yet but will do so soon and test this PR as well
Thanks for the effort @rj-david

**Comment by rj-david** [comment]
> Glad this is resolved with changes to cordova-plugin-meteor-webapp _only_ (at least for the Meteor part)

There were also a few quick changes to update this to support Swift 5.0

But I'm not 100% sure if there is a need to update to cordova-ios 5.0.0; which might require cordova-lib 9.0.0; which will pin cordova-android to 8.0.0. cordova-android deprecated a function affecting one of my plugins. I will run the test with cordova-ios 5.0.0 on Monday

**Comment by rj-david** [comment]
I'm retracting this as it was mentioned in the issue thread that there are other errors when moving to Swift 4 that must be fixed. Need someone who are really adept with swift

**Comment by goodspeed666** [comment]
Hi @rj-david, 
It's possible to implement cordova-ios 5.0.0 quickly ?
Coz Xcode 10.1 can not test iOS 12.2 above.
Thank you.

**Comment by rj-david** [comment]
@goodspeed666 please check this: https://github.com/meteor/cordova-plugin-meteor-webapp/pull/78

This has been released as https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.8.1-issue-10516.0

**Comment by goodspeed666** [comment]
Hi @rj-david ,

Yes, I have tried #78 before.
When I run build, it will be occur this error.

> /Users/goodspeed/.meteor/packages/static-html/.1.2.2.p8ac5g.7xso++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
>       throw error;
>       ^

I try to remove static-html, and run build again.
It will no error, but the screen will blank on the mobile.

When I reinstall static-html `meteor add static-html@1.2.2`, the error will the same as before.
Is the `static-html` package rename ?
I can not search for it.

Thank you for your response.

**Comment by rj-david** [comment]
Not familiar with the internals of this package. Better to post as a new issue in the main Meteor repo

**Pull request closed without merging**
