### PR TITLE
Prevent from using incompletely downloaded files

### PR DESCRIPTION
**Pull request by wojtkowiak**
This deals with the situation in which an incompletely downloaded file
is saved to disk and later treated like a fully downloaded one. This
can happen on slow, disconnecting internet connections.

Fixes https://github.com/meteor/meteor/issues/9387

I would happily add tests to it but I have tried several times to run them and I still do not know how to do that while developing this plugin. (https://github.com/meteor/cordova-plugin-meteor-webapp/issues/8)

### CODE REVIEW

**Comment by abernix** [comment]
It seems like it would be preferable to avoid having a partially written file at all by writing files to a temporary file and moving them into their final and desired place (atomically) when the download is successfully completed.

**Comment by wojtkowiak** [comment]
> Would that be a reasonable alternate approach here?

Yes, I agree, will try to get back to it next week.

BTW big thanks for Cordova getting some attention 🙂

**Comment by KoenLav** [comment]
@wojtkowiak any progress on this one?

**Comment by KoenLav** [comment]
@wojtkowiak any progress?

I'm sorry to keep asking, but we keep running into these issues and I don't feel at home with this portion of the Meteor codebase, still.

**Comment by wojtkowiak** [comment]
> Yes, I agree, will try to get back to it next week.

I need to work on my definition of a week...
Updated to using temporary files, it's so much shorter now 🙂

**Comment by brucejo75** [comment]
Is this ready to roll?  Will it show up in 1.8.1?  I am seeing this [issue](https://github.com/meteor/meteor/issues/10288) during development and my users have reported the problem on my deployed bits.

**Comment by brucejo75** [comment]
@benjamn, @wojtkowiak,

Is this ready to pull in?  Is it stuck on the build test failures?

**Pull request merged**
