### PR TITLE
Update GCDWebServer to latest version.

### PR DESCRIPTION
**Pull request by abernix**
In an effort to bring the iOS `GCDWebServer` tree up to date, this PR is a result of running:

    git subtree pull --prefix src/ios/GCDWebServer https://github.com/swisspol/GCDWebServer.git master --squash

I'm currently ✈️ and unable to test this properly, but I hope that this will make it more reasonable to review and land https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30.  Comments / critique / testing, very welcome!

/cc @macrozone

### CODE REVIEW

**Comment by macrozone** [comment]
@abernix does it include https://github.com/swisspol/GCDWebServer/pull/299 ?

unforunatly, this has not been merged yet

**Comment by abernix** [comment]
@macrozone No, it doesn't include it.  This was just to get us out of the backlog of fixes first, before applying new logic of our own.  I'm not comfortable backporting swisspol/GCDWebServer#299 without bringing (and preserving) all the other (unrelated) history which was required to make #30 work.  I think we'll be in a much better position to consider #30 when this is done.

As you probably have a more active developer experience with Cordova than I do, if you could help test this, I'd really appreciate it.  I think you should be able to:

    meteor add cordova:cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#cf35f09321096dd4292fb1e6e633aec9c2860e45

And then run things as usual?

**Comment by abernix** [comment]
I had a little extra time to try my own suggestion above, but it failed due to a number of Swift compilation errors, so I guess this needs further investigation.  Please do try to take a peak if you get a chance!

**Comment by abernix** [comment]
If anyone is more inclined to jump into Swift code than I am, I would encourage them to tackle my suggestion above (which I had to walk away from, for the time being at least).

**Comment by macrozone** [comment]
@abernix anyone on the mdg team who could help on this?

Also can you try to reactive https://github.com/swisspol/GCDWebServer/pull/299 ?

**Comment by abernix** [comment]
@macrozone At the current time, there is not.  I'd say this is very close to getting merged, but there were some symbols that were renamed, etc. for compatibility.  They can be seen when running `meteor run ios-device` and building in XCode, and if I recall, there were not _heaps_ of problems, just a few blockers.

**Comment by KoenLav** [comment]
Suggest closing this PR and moving the discussion to https://github.com/meteor/GCDWebServer

**Comment by benjamn** [comment]
Superseded by #45.

**Pull request closed without merging**
