### PR TITLE
Fixes for HCP errors

### PR DESCRIPTION
**Pull request by KoenLav**
Contains changes made by @bmanturner aiming to fix HCP issues.

### CODE REVIEW

**Comment by KoenLav** [comment]
@bmanturner could you (further) clarify your changes so they can maybe be merged back into this repository?

**Comment by wojtkowiak** [comment]
Most of those changes are from here:
https://github.com/matdurand/cordova-plugin-meteor-webapp/commit/ef7b999849ff8742f685b31e0348a492e36cc441
(credits @matdurand)

First is the blacklist retry: https://github.com/matdurand/cordova-plugin-meteor-webapp/commit/ef7b999849ff8742f685b31e0348a492e36cc441#diff-5a6122e074f120eb07eb0a3298e331d8R71 (for both ios/android) - it basically allows to do one retry before it blacklists the version. It would be nice if we could specify how many times it should be retried before getting blacklisted.

Second is the the method that allows you to change to the pending version https://github.com/matdurand/cordova-plugin-meteor-webapp/commit/ef7b999849ff8742f685b31e0348a492e36cc441#diff-e9a5d10fe686c1ff2b69a5030c60c165R203 
From my research it seems to be safe to do that in the `Reload.onReload` and it is far better than switching when the onReset is fired in the webview which is the current mechanism. This fixes this issue which I also encountered (https://github.com/meteor/cordova-plugin-meteor-webapp/issues/4). However calling it would have to baked deeper in the Reload after all the callbacks from onReload are fired and we know we are doing a reload. Now if you add this as callback to onReload there is chance a callback that would be fired after would prevent HCP which is not good,

More on those changes made by @matdurand here https://github.com/meteor/meteor/issues/8063

Maybe it would be better to extract those to separate PRs. @abernix let me know. I can confirm that those combined with the other fixes solved almost all issues with HCP I did experience.

**Comment by hwillson** [comment]
Just dropping a reference - this PR will fix https://github.com/meteor/meteor/issues/8063.

**Comment by menelike** [comment]
We had to use this in production and after several months we did not have one single user with an outdated bundle version. We would have been doomed without this PR, thanks a lot @KoenLav 

IMHO this issue should gain more attention from the maintainers.

**Comment by KoenLav** [comment]
@menelike thanks, good to see it resolves your issues, but I guess this requires some more work before it can be merged. 

@wojtkowiak first of all enjoy your holiday!

But after, maybe you have some time to revisit this?

@abernix @hwillson I agree with @menelike; we're almost there, let's make it happen :)

**Comment by bmanturner** [comment]
@KoenLav  Sorry for the delay. I'll check my notification settings.

@wojtkowiak Was right in his accreditation. This was not my own work, and my git-fu isn't up to par enough to cherry pick his work. Sorry for the confusion.

**Comment by KoenLav** [comment]
@wojtkowiak do you think this PR should be closed in favor of a certain changeset in your (forked) repo?

**Comment by KoenLav** [comment]
@benjamn @abernix we've been using these changes, which @wojtkowiak presented in separate PRs recently, in production and haven't seen any more errors.

Closing this PR, please do take a look at the others!

**Pull request closed without merging**
