### PR TITLE
Panter

### PR DESCRIPTION
**Pull request by KoenLav**
I removed all the line ending changes etc. and kept all changes which panter made to the GCDWebServer update to make it working again.

This is UNTESTED.

Comments are welcome, but this should prove easier to merge (by applying the changes incrementally).

### CODE REVIEW

**Comment by macrozone** [comment]
thx @KoenLav ,

sorry i have been busy with other projects and the forked version did its job on our app...

thanks for putting this up! i will try to test it as well

**Comment by macrozone** [comment]
@KoenLav just tested it, but it does not compile in xcode, i get some swift errors:

```

Showing All Messages
/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:385:13: Initializer for conditional binding must have Optional type, not 'String'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:392:28: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:400:13: Initializer for conditional binding must have Optional type, not 'String'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:412:29: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:420:13: Initializer for conditional binding must have Optional type, not 'String'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:432:31: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:440:13: Initializer for conditional binding must have Optional type, not 'String'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:453:28: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

/Users/macrozone/git/panter/pvl/biketowork/app/.meteor/local/cordova-build/platforms/ios/bike to work dev/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift:513:33: Nil cannot be assigned to type 'Date'

```

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:385:13: Initializer for conditional binding must have Optional type, not 'String'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:392:28: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:400:13: Initializer for conditional binding must have Optional type, not 'String'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:412:29: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:420:13: Initializer for conditional binding must have Optional type, not 'String'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:432:31: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:440:13: Initializer for conditional binding must have Optional type, not 'String'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:453:28: Cannot use optional chaining on non-optional value of type 'GCDWebServerRequest'

cordova-plugin-meteor-webapp/WebAppLocalServer.swift:513:33: Nil cannot be assigned to type 'Date'


```

**Comment by KoenLav** [comment]
@macrozone I expected as much...

What I simply did was look at all the open pull requests and 'cherry pick' them into presentable PRs.

I don't have sufficient experience with native coding to actually work this out, but I was trying to provide a head start for others.

**Comment by macrozone** [comment]
@KoenLav actually, its not that hard to fix, but i need some swift knowledge...

e.g. 513 is because lastModifiedDate is non nullable anymore, but meteor sets it to nil. Fix is to remove the redeclaration to non-nullable,

but i am stuck with the `Initializer for conditional binding must have Optional type, not 'String'` at the moment as i don't know swift.

**Comment by macrozone** [comment]
@KoenLav  i tested the other pr https://github.com/meteor/cordova-plugin-meteor-webapp/pull/42, is that correct?

i now open up another PR where i try to fix these errors... (i need a coffee ☕️ )

**Comment by KoenLav** [comment]
Closed due to moving the dependency on GCDwebserver to a submodule.

**Pull request closed without merging**
