### PR TITLE
Feature/restart gcd webserver

### PR DESCRIPTION
**Pull request by macrozone**
applies https://github.com/swisspol/GCDWebServer/pull/299 as well as https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25

and fixes https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27

I just copied the source code from https://github.com/swisspol/GCDWebServer/pull/299 into this project, not sure if this has some kind of dependency management?

you can install and try this fix with: 

cordova-plugin-meteor-webapp@https://github.com/panter/cordova-plugin-meteor-webapp.git#7bb095ce393d17f662cc6bb596ce91acf743d17a

~meteor 1.6.1 users use: cordova-plugin-meteor-webapp@https://github.com/panter/cordova-plugin-meteor-webapp.git#574e11822890a773cc307ab068e1c745384c80a2 (carefull this version is NOT compatible with meteor < 1.6.1)~ (this has been fixed in meteor 1.6.1)

### CODE REVIEW

**Comment by Wade-BuildOtto** [comment]
so far so good, I opened my app this morning and it opened up quicker then I have ever seen, like it was ready to use, few more days of trials and I think we can call this fixed.

crossing fingers, 
Thank you so much,

**Comment by macrozone** [comment]
crossing fingers too, had also no problem anymore ;-)

**Comment by abernix** [comment]
@macrozone Thank you very much for taking a look at this.  I would love to get this reviewed, merged and released, possibly in Meteor 1.5.2 and along with other Cordova updates.

That said, it would be substantially easier to review this pull request (which must be reviewed carefully, in its entirety) if it was broken down a lot more.  As of right now this is a bit daunting and slightly risky.

The PR you linked to is quite a bit more brief.  Maybe a better approach here would be to apply the incremental changes (which have likely been made to the master repository over a longer period of time?) automatically (for example, using [`git apply`](https://git-scm.com/docs/git-am) or [`git am`](https://git-scm.com/docs/git-am) with the `-p` argument to apply all their patches to the `GCDWebServer` directory).  This would bring this repository up to date, while preserving the logical commits and changes from the Git history, and then we could apply this last (outstanding PR)?

Alternatively, it would be far easier to review this if:

* Formatting (whitespace, new-lines, etc.) changes were submitted in a separate PR (They are valuable, and I'm happy to accept them, but even with GitHub's [`?w=1` query parameter](https://github.com/blog/967-github-secrets) (which tries to ignore whitespace changes), there is a lot of non-functionality change in here.
* Specific functional changes were in separate commits.

As you may not have been the one who added all the formatting and other functionality changes, the previous approach I suggested may be more reasonable.

Thoughts?

**Comment by macrozone** [comment]
@abernix yeah, it's still "make it ~run make it right make it fast~", i just copied the code.

I try to give my best to do this cleaner, but i have to familiarize myself with these advanced git workflows.

I would suggest to first review & merge https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25

as I also included this. So I could focuse on applying the gcd-webserver fixes

**Comment by abernix** [comment]
@macrozone Any updates on this?

**Comment by abernix** [comment]
Assuming my changes from #31 work okay, this can be rebased on that and evaluated much more efficiently – though it would still be great if https://github.com/swisspol/GCDWebServer/pull/299 could get the blessing of the original author and be officially merged!

**Comment by macrozone** [comment]
@abernix I will give it a try this week, stay tuned.

**Comment by dylanjaye** [comment]
Just wanted to confirm this fix.  I was having issues with Meteor failing to load resources on iOS after locking the screen.

Incorporating this cordova plugin:  cordova-plugin-meteor-webapp@https://github.com/panter/cordova-plugin-meteor-webapp.git#7bb095ce393d17f662cc6bb596ce91acf743d17a

as suggested by @macrozone has completely fixed my issue.  +1

**Comment by Nauzer** [comment]
@abernix @macrozone how is it looking? Any chance this might get into 1.5.2?
Since 1.5.2 is a minor version can it contain cordova plugin updates?

**Comment by macrozone** [comment]
@Nauzer we should merge https://github.com/meteor/cordova-plugin-meteor-webapp/pull/31 first and then apply https://github.com/swisspol/GCDWebServer/pull/299

it would be easier if https://github.com/swisspol/GCDWebServer/pull/299 would be merged in the original repository though, so maybe you leave an upvote there  ;-)

**Comment by KoenLav** [comment]
@macrozone could you implement your changes (not to GCD webserver, but to the Meteor specific code) into a branch based off this one: https://github.com/meteor/cordova-plugin-meteor-webapp/tree/replace-GCDWebServer-copy-with-submodule ?

**Comment by benjamn** [comment]
@macrozone Do you think you could rebase the key changes in this PR against the current `master` branch (version 1.5.2), bearing in mind that `src/ios/GCDWebServer` is now a git submodule (#45)?

**Comment by KoenLav** [comment]
@benjamn I created a PR which covers the changes made in GCDWebServer#299 here:

https://github.com/meteor/GCDWebServer/pull/2

**Comment by macrozone** [comment]
sorry guys, i was skiing in the mountains ;-)

@KoenLav, i can test it in the next week, but from the code, it looks clean to me.

**Comment by KoenLav** [comment]
@macrozone any progress?

**Comment by KoenLav** [comment]
@macrozone do you think this PR still provides any value, or rather it should be closed?

**Comment by macrozone** [comment]
@KoenLav

The changes in this PR should have landet already in another PR

**Pull request closed without merging**
