### PR TITLE
Continue running the local web server in the background

### LINKED ISSUE #24: GCD local web server should run in the background
In normal app startup, the app is started in the foreground, the WebAppLocalServer plugin starts the GCD local web server, the Cordova WKWebViewEngine plugin starts the web view, and the Meteor app loads from the local web server.

The GCD local web server is stopped when the application enters the background.  (See https://github.com/awwx/meteor-bg-web-bug for a reproduction).

When an app enters the background, typically iOS will suspend the app after a couple of seconds, so most applications may not notice that the local web server isn't running (the app won't be doing anything, much less making requests to the local web server, when it's suspended).

However, iOS apps can request additional running time in the background.

An iOS app can also be *started* in the background.

For example, an iOS app can request that a file be uploaded or downloaded in the background, so that the file transfer can run even if the app itself isn't running.  The app can have iOS notify the app when the file transfer completes (so that, for example, it can record that the file transfer finished or show a notification to the user).  If the app isn't running at the time the file transfer completes, iOS will start the app in the background to provide the notification.

I had [previously](https://github.com/meteor/cordova-plugin-meteor-webapp/pull/9) noted that the app version was being blacklisted when the app started in the background, and I offered a PR to not start the backlist timer.  However the *real* issue as it turns out is that Meteor is attempting to start up in the web view... but Meteor fails to load because the GCD web server isn't running at that point.

(Specifically, the CDVViewController `loadRequest:` method is called, and the WKWebViewEngine `didStartProvisionalNavigation:` method is triggered, but it never makes it to the WKWebViewEngine `didFinishNavigation:` method or to the WebAppLocalServer `pageDidLoad` method.)

If the user then brings the app into the *foreground* (for example, if they saw the notification that the file upload completed and opened the app), at that point the app is hung at the splash screen because the web view had already tried and failed to load the app.

We can tell the GCD local server to not stop in the background:

```
    let options = [
      GCDWebServerOption_Port: NSNumber(value: localServerPort as UInt),
      GCDWebServerOption_BindToLocalhost: true,
      GCDWebServerOption_AutomaticallySuspendInBackground: false]  // <-- added
    try localServer.start(options: options)
```

### PR DESCRIPTION
**Pull request by awwx**
Fixes #24.

### CODE REVIEW

**Comment by lorensr** [comment]
Issue description makes sense to me, and while I haven't tested it, looks like it's working for two people. @abernix do you have merge rights on this repo?

**Comment by abernix** [comment]
Sorry, just saw this!  I do have merge rights, but I just need a little more assurance.  I commented in https://github.com/meteor/cordova-plugin-meteor-webapp/issues/24#issuecomment-292901368.

**Comment by paulincai** [comment]
Hi there,

could this have anything to do with this behavior? https://www.youtube.com/watch?v=SQDFox62q0A. I have more details in the Meteor Forum at: https://forums.meteor.com/t/meteor-ios-app-screen-flicker-after-resume-1-4-4-1/35942
I just don't seem to relate the issue to anything in the code or other experiences of other people.

Cheers.

**Comment by awwx** [comment]
@paulincai  I don't think so, this bug is if a Meteor app is started in the background the app hangs.

**Comment by paulincai** [comment]
@awwx thanks a lot man for your reply. After many many hours I found the issue. These people should be fined by the community... :)). I removed this one and all ok now: https://atmospherejs.com/ostrio/user-status

**Comment by Wade-BuildOtto** [comment]
sorry, what does that mean, something from user-status plugin was causing an issue? I am using mizzao:user-status.

**Comment by paulincai** [comment]
@Wade-BuildOtto that's right. When I removed it everything went back to normal. How do you feel about mizzao:user-status? I see there hasn't been updated in a long time and this is the only reason I didn't use it. Since I only need an online/offline thing, I went for konecty:user-presence

**Comment by Wade-BuildOtto** [comment]
It covers all the bases, I like it for knowing which page the user is on,
so I can follow them thru the process so if they need help usually starts
with are you on the correct page. but I might dump it to see if It can
remove the reload issue.

**Comment by paulincai** [comment]
@Wade-BuildOtto I think we are a bit off-topic on this particular page but I would love to know if this fixes your issue and perhaps we could open a page..something to note down packages and their issues. If the community could maintain this would probably be motivating for authors to actually test and maintain their packages.

**Pull request merged**
